import "./bootstrap";
import "./burger_button_menu_mobile";
import "./mobile_menu";
import "./header";
import "./counter_main";
import "./main_hero_home";
import "./section_services";
import "./map";
import "./competencies_slider";
